apiVersion: v1
kind: ConfigMap
metadata:
  name: ty-multiverse-backend-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://*****/peoplesystem"
  SPRING_DATASOURCE_USERNAME: "****"
  SPRING_DATASOURCE_PASSWORD: "****"
  SPRING_PROFILES_ACTIVE: "platform" 
  SERVER_PORT: "8080"      
  LOGGING_LEVEL: "INFO"         
  LOGGING_LEVEL_SPRINGFRAMEWORK: "INFO"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ty-multiverse-backend
  labels:
    app.kubernetes.io/name: ty-multiverse-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ty-multiverse-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ty-multiverse-backend
    spec:
      containers:
      - name: ty-multiverse-backend
        image: papakao/ty-multiverse-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: ty-multiverse-backend-config
              key: SERVER_PORT
        - name: SPRING_PROFILES_ACTIVE
          value: "platform"
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: ty-multiverse-backend-config
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: ty-multiverse-backend-config
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: ty-multiverse-backend-config
              key: SPRING_DATASOURCE_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: ty-multiverse-backend
  labels:
    app.kubernetes.io/name: ty-multiverse-backend
spec:
  selector:
    app.kubernetes.io/name: ty-multiverse-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ty-multiverse-backend-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: peoplesystem.tatdvsonorth.com
    http:
      paths:
      - path: /tymb
        pathType: Prefix
        backend:
          service:
            name: ty-multiverse-backend
            port:
              number: 80
