apiVersion: v1
kind: Secret
metadata:
  name: ty-multiverse-backend-secrets
type: Opaque
stringData:
  SPRING_PEOPLE_DATASOURCE_URL: "${SPRING_PEOPLE_DATASOURCE_URL}"
  SPRING_PEOPLE_DATASOURCE_USERNAME: "${SPRING_PEOPLE_DATASOURCE_USERNAME}"
  SPRING_PEOPLE_DATASOURCE_PASSWORD: "${SPRING_PEOPLE_DATASOURCE_PASSWORD}"
  REDIS_HOST: "${REDIS_HOST}"
  REDIS_CUSTOM_PORT: "${REDIS_CUSTOM_PORT}"
  REDIS_PASSWORD: "${REDIS_PASSWORD}"
  REDIS_QUEUE_TYMB: "${REDIS_QUEUE_TYMB}"
  KEYCLOAK_AUTH_SERVER_URL: "${KEYCLOAK_AUTH_SERVER_URL}"
  PUBLIC_REALM: "${PUBLIC_REALM}"
  PUBLIC_CLIENT_ID: "${PUBLIC_CLIENT_ID}"
  KEYCLOAK_CREDENTIALS_SECRET: "${KEYCLOAK_CREDENTIALS_SECRET}"
  PUBLIC_TYMB_URL: "${PUBLIC_TYMB_URL}"
  PUBLIC_FRONTEND_URL: "${PUBLIC_FRONTEND_URL}"
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: ty-multiverse-backend-config
data:
  SPRING_PROFILES_ACTIVE: "platform" 
  SERVER_PORT: "8080"
  LOGGING_LEVEL: "INFO"
  LOGGING_LEVEL_SPRINGFRAMEWORK: "INFO"
  PROJECT_ENV: "platform"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ty-multiverse-backend
  labels:
    app.kubernetes.io/name: ty-multiverse-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: ty-multiverse-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ty-multiverse-backend
    spec:
      containers:
      - name: ty-multiverse-backend
        image: papakao/ty-multiverse-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: ty-multiverse-backend-config
              key: SERVER_PORT
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: ty-multiverse-backend-config
              key: SPRING_PROFILES_ACTIVE
        - name: LOGGING_LEVEL
          valueFrom:
            configMapKeyRef:
              name: ty-multiverse-backend-config
              key: LOGGING_LEVEL
        - name: LOGGING_LEVEL_SPRINGFRAMEWORK
          valueFrom:
            configMapKeyRef:
              name: ty-multiverse-backend-config
              key: LOGGING_LEVEL_SPRINGFRAMEWORK
        - name: SPRING_PEOPLE_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: ty-multiverse-backend-secrets
              key: SPRING_PEOPLE_DATASOURCE_URL
        - name: SPRING_PEOPLE_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: ty-multiverse-backend-secrets
              key: SPRING_PEOPLE_DATASOURCE_USERNAME
        - name: SPRING_PEOPLE_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ty-multiverse-backend-secrets
              key: SPRING_PEOPLE_DATASOURCE_PASSWORD
        - name: KEYCLOAK_AUTH_SERVER_URL
          valueFrom:
            secretKeyRef:
              name: ty-multiverse-backend-secrets
              key: KEYCLOAK_AUTH_SERVER_URL
        - name: PUBLIC_REALM
          valueFrom:
            secretKeyRef:
              name: ty-multiverse-backend-secrets
              key: PUBLIC_REALM
        - name: PUBLIC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: ty-multiverse-backend-secrets
              key: PUBLIC_CLIENT_ID
        - name: KEYCLOAK_CREDENTIALS_SECRET
          valueFrom:
            secretKeyRef:
              name: ty-multiverse-backend-secrets
              key: KEYCLOAK_CREDENTIALS_SECRET
        - name: PUBLIC_TYMB_URL
          valueFrom:
            secretKeyRef:
              name: ty-multiverse-backend-secrets
              key: PUBLIC_TYMB_URL
        - name: PUBLIC_FRONTEND_URL
          valueFrom:
            secretKeyRef:
              name: ty-multiverse-backend-secrets
              key: PUBLIC_FRONTEND_URL
        - name: PROJECT_ENV
          valueFrom:
            configMapKeyRef:
              name: ty-multiverse-backend-config
              key: PROJECT_ENV
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: ty-multiverse-backend-secrets
              key: REDIS_HOST
        - name: REDIS_CUSTOM_PORT
          valueFrom:
            secretKeyRef:
              name: ty-multiverse-backend-secrets
              key: REDIS_CUSTOM_PORT
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ty-multiverse-backend-secrets
              key: REDIS_PASSWORD
        - name: REDIS_QUEUE_TYMB
          valueFrom:
            secretKeyRef:
              name: ty-multiverse-backend-secrets
              key: REDIS_QUEUE_TYMB
---

apiVersion: v1
kind: Service
metadata:
  name: ty-multiverse-backend
  labels:
    app.kubernetes.io/name: ty-multiverse-backend
spec:
  selector:
    app.kubernetes.io/name: ty-multiverse-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ty-multiverse-backend-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: peoplesystem.tatdvsonorth.com
    http:
      paths:
      - path: /tymb
        pathType: Prefix
        backend:
          service:
            name: ty-multiverse-backend
            port:
              number: 80
