apiVersion: v1
kind: Secret
metadata:
  name: ty-multiverse-backend-secrets
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "${SPRING_DATASOURCE_URL}"
  SPRING_DATASOURCE_USERNAME: "${SPRING_DATASOURCE_USERNAME}"
  SPRING_DATASOURCE_PASSWORD: "${SPRING_DATASOURCE_PASSWORD}"
  REDIS_HOST: "${REDIS_HOST}"
  REDIS_CUSTOM_PORT: "${REDIS_CUSTOM_PORT}"
  REDIS_PASSWORD: "${REDIS_PASSWORD}"
  REDIS_QUEUE_TYMB: "${REDIS_QUEUE_TYMB}"
  KEYCLOAK_AUTH_SERVER_URL: "${KEYCLOAK_AUTH_SERVER_URL}"
  KEYCLOAK_REALM: "${KEYCLOAK_REALM}"
  KEYCLOAK_CLIENT_ID: "${KEYCLOAK_CLIENT_ID}"
  KEYCLOAK_CREDENTIALS_SECRET: "${KEYCLOAK_CREDENTIALS_SECRET}"
  URL_ADDRESS: "${URL_ADDRESS}"
  URL_FRONTEND: "${URL_FRONTEND}"
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: ty-multiverse-backend-config
data:
  SPRING_PROFILES_ACTIVE: "platform" 
  SERVER_PORT: "8080"
  LOGGING_LEVEL: "INFO"
  LOGGING_LEVEL_SPRINGFRAMEWORK: "INFO"
  PROJECT_ENV: "platform"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ty-multiverse-backend
  labels:
    app.kubernetes.io/name: ty-multiverse-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: ty-multiverse-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ty-multiverse-backend
    spec:
      containers:
      - name: ty-multiverse-backend
        image: papakao/ty-multiverse-backend:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: ty-multiverse-backend-config
        - secretRef:
            name: ty-multiverse-backend-secrets
---

apiVersion: v1
kind: Service
metadata:
  name: ty-multiverse-backend
  labels:
    app.kubernetes.io/name: ty-multiverse-backend
spec:
  selector:
    app.kubernetes.io/name: ty-multiverse-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ty-multiverse-backend-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: peoplesystem.tatdvsonorth.com
    http:
      paths:
      - path: /tymb
        pathType: Prefix
        backend:
          service:
            name: ty-multiverse-backend
            port:
              number: 80
